# spring:
#   main:
#     allow-circular-references: true
#     lazy-initialization: false
#   application:
#     name: HospitalManagementSystem
#     baseUrl: http://localhost:8080
#   # Database
#   datasource:
#     tomcat:
#       max-active: 10
#       max-idle: 5
#       min-idle: 2
#       initial-size: 5
#       remove-abandoned: true
#     url: jdbc:postgresql://localhost:5432/HospitalManagementSystem
#     username: postgres
#     password: postgres
#   # JPA properties
#   jpa:
#     hibernate:
#       ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#     show-sql: true
#     database: postgresql
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     open-in-view: false
#     generate-ddl: true
#   jackson:
#     serialization:
#       FAIL_ON_EMPTY_BEANS: false

spring:
  main:
    allow-circular-references: true
    lazy-initialization: false
  application:
    name: HospitalManagementSystem
    baseUrl: http://localhost:4000
  # Database
  datasource:
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
    url: jdbc:mysql://localhost:3306/HMS_java
    username: root
    password: RootPass0044$
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update    # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true
    # Enable SQL script execution
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      # data-locations: classpath:sql/data.sql
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
